use customer_behaviour_project;

select * from customer limit 10;

-- 1] What is the total revenue generated by male vs female customers ?
select gender, sum(purchase_amount) as Revenue 
from customer
group by gender;

-- 2] Which customers used a discount but still spent more than the average purchase amount ?
select customer_id, purchase_amount
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- 3] Which are the top 5 products with the highest average review rating ?
select item_purchased, round(avg(review_rating),2) as Review_Rating
from customer 
group by item_purchased
order by Review_Rating
desc limit 5 ;

-- 4] Compare the average Purchase Amounts between Standard & Express Shipping.
select shipping_type, round(avg(purchase_amount),2)
from customer 
where shipping_type in ('Standard','Express')
group by shipping_type;

-- 5] Do subscribed customers spend more ? Compare average spend & total revenue between sub.scribers and non-subscribers
select subscription_status,count(customer_id) as Total_Customers,
round(avg(purchase_amount),2) as Avg_Spend, sum(purchase_amount) as Total_Revenue
from customer 
group by subscription_status
order by Total_Revenue, Avg_Spend;

-- 6] Which 5 products have the highest percentage of purchases with discounts applied ?
select item_purchased,
round(sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*)*100,2) as Discount_Rate
from customer 
group by item_purchased
order by Discount_Rate desc
limit 5;

-- 7] Segment customers into New, Returning and loyal based on their total number of previous purchases, & show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'loyal'
    end as customer_segement
from customer 
)

select customer_segement, count(*) as 'Number of Customers'
from customer_type 
group by customer_segement;

-- 8] What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT 
        category, 
        item_purchased, 
        COUNT(customer_id) AS Total_Orders, 
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC  -- Usually DESC for ranking
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
select item_rank, category, item_purchased, Total_Orders 
from item_counts
where item_rank <= 3;

-- 9] Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- 10] What is the revenue contribution of each age group ?
select age_group, sum(purchase_amount) as Total_Revenue
from customer 
group by age_group
order by Total_Revenue desc;

